import os

from .cli_helpers import run_cli


FALLBACK_TEXT = "This is an example AI-generated phrasing suggestion."
FAKE_LLM_OUTPUT = "This phrasing was generated by the LLM."


def test_shadow_mode_proposal_text_is_not_fallback():
    """
    Liveness invariant (Phase 5.7):

    When shadow-mode LLM execution is enabled,
    successful LLM generation must replace
    fallback proposal text.
    """

    os.environ["USE_LLM_SHADOW_MODE"] = "1"
    os.environ["LLM_SHADOW_TEST_OUTPUT"] = FAKE_LLM_OUTPUT

    out, err = run_cli(["proposals", "show", "1"])

    assert err == ""
    assert FALLBACK_TEXT not in out
    assert FAKE_LLM_OUTPUT in out
